# Clase 7: Matrices y DataFrames

**Objetivo de la clase:** antes de entrar a Unidad 2 (modularidad y recursión), necesitamos una herramienta nueva para representar datos: **estructuras de dos dimensiones**.

Hasta ahora hemos trabajado con:
- Variables individuales (un número, un string)
- Listas (una secuencia de valores)

Hoy damos el salto a **tablas de datos**: filas y columnas. Esto nos va a servir para todo lo que viene después, incluyendo el sistema de notas que hemos ido construyendo.

## Matrices

Una matriz es, conceptualmente, una tabla de números organizada en **filas** y **columnas**.

Python no tiene un tipo "matriz" propio, pero podemos simularla con una **lista de listas**: cada lista interna es una fila.

In [1]:
# Una matriz de 3 filas x 3 columnas, representada como lista de listas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(matriz)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

### Acceso a elementos

Para acceder a un elemento necesitamos **dos índices**: fila y columna.

In [2]:
# Elemento en la fila 0, columna 2 (recordar: los índices parten en 0)
print(matriz[0][2])  # 3

# Fila completa
print(matriz[1])  # [4, 5, 6]

3
[4, 5, 6]

In [3]:
# ¿Cuántas filas y columnas tiene?
filas = len(matriz)
columnas = len(matriz[0])

print(f"La matriz tiene {filas} filas y {columnas} columnas")

La matriz tiene 3 filas y 3 columnas

### Recorrer una matriz

Para recorrer todos los elementos necesitamos **dos bucles anidados**: uno para las filas, otro para las columnas.

In [4]:
suma_total = 0

for fila in matriz:
    for elemento in fila:
        suma_total += elemento

print(f"Suma de todos los elementos: {suma_total}")

Suma de todos los elementos: 45

In [5]:
# Ejercicio rápido: sumar los elementos de cada fila por separado
for fila in matriz:
    suma_fila = sum(fila)
    print(f"Fila {fila} -> suma = {suma_fila}")

Fila [1, 2, 3] -> suma = 6
Fila [4, 5, 6] -> suma = 15
Fila [7, 8, 9] -> suma = 24

### El problema

Esto funciona, pero para hacer algo tan simple como sumar filas, sacar promedios por columna, o multiplicar matrices, el código con bucles anidados se vuelve **largo y propenso a errores**.

Además, las listas no obligan a que todas las filas tengan el mismo largo (podríamos tener una matriz "mal formada" sin darnos cuenta).

Para esto existe **NumPy**: una librería especializada en trabajar con arreglos numéricos de forma eficiente y con menos código.

## NumPy

NumPy (*Numerical Python*) es la librería estándar para trabajar con arreglos (arrays) numéricos en Python.

In [6]:
import numpy as np

# Creamos un array a partir de nuestra matriz anterior
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matriz_np)
print(type(matriz_np))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>

### Forma y dimensiones

En vez de calcular `len()` manualmente, NumPy nos da esta información directamente.

In [7]:
print(matriz_np.shape) # (filas, columnas)
print(matriz_np.ndim) # número de dimensiones

(3, 3)
2

In [11]:
# Otras formas de crear arrays
ceros = np.zeros((2, 4)) # matriz de 2x4 llena de ceros
secuencia = np.arange(0, 10, 2)  # números del 0 al 10, de 2 en 2

print(ceros)
print(secuencia)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 2 4 6 8]

### Indexación y slicing en 2D

En NumPy no necesitamos dos corchetes: usamos `matriz[fila, columna]`.

In [13]:
print(matriz_np[0, 2]) # fila 0, columna 2 (3)
print(matriz_np[:, 1]) # todas las filas, columna 1
print(matriz_np[1, :]) # fila 1 completa

3
[2 5 8]
[4 5 6]

### Operaciones vectorizadas

Esto es lo que hace valiosa a NumPy: podemos operar sobre toda la matriz **sin escribir bucles**.

In [14]:
print(matriz_np.sum()) # suma de todos los elementos
print(matriz_np.sum(axis=0)) # suma por columna
print(matriz_np.sum(axis=1)) # suma por fila
print(matriz_np.mean(axis=1)) # promedio por fila

45
[12 15 18]
[ 6 15 24]
[2. 5. 8.]

## Clásico

In [5]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

C = A + B

print(C)

[[ 6  8]
 [10 12]]

In [6]:
# Multiplicación MATRICIAL
C = A @ B
print(C)

[[19 22]
 [43 50]]

In [7]:
# Multiplicación elemento por elemento
C = A * B
print(C)

[[ 5 12]
 [21 32]]

In [8]:
escalar = 3

C = escalar * A
print(C)

[[ 3  6]
 [ 9 12]]

In [9]:
# Funciona a la inversa
C = A * escalar
print(C)

[[ 3  6]
 [ 9 12]]

## Pandas y DataFrames

NumPy es ideal para matrices **numéricas**. Pero en la práctica, los datos rara vez son solo números: tenemos nombres, RUT, categorías, fechas, mezclados con números.

Para eso existe **Pandas**, que agrega dos cosas clave sobre NumPy:
- Columnas con **nombre** (no solo índice numérico)
- Columnas con **tipos distintos** (texto, número, fecha, etc.) en la misma tabla

In [16]:
import pandas as pd

# Un DataFrame se puede crear directamente desde un diccionario:
# cada llave es una columna, cada lista son los valores de esa columna
datos = {
    "nombre": ["Anahís", "Vicente", "Alonzo"],
    "nota1": [1.5, 3.9, 6.8],
    "nota2": [2.2, 4.1, 6.5]
}

df = pd.DataFrame(datos)
print(df)

    nombre  nota1  nota2
0   Anahís    1.5    2.2
1  Vicente    3.9    4.1
2   Alonzo    6.8    6.5

### Leer datos desde un archivo

En la práctica casi nunca escribimos los datos a mano: los leemos desde un archivo. Vamos a usar `notas_estudiantes.csv`, que contiene notas de un curso.

In [25]:
notas = pd.read_csv("notas_estudiantes.csv", encoding = "UTF-8")
notas

               nombre         rut  nota1  nota2  nota3
0         Anahis Friz  12345678-1    1.5    2.2    4.8
1     Vicente Araneda  12345678-2    3.9    4.1    4.5
2          Alonso Cea  12345678-3    6.8    6.5    7.0
3  Alenger Betancourt  12345678-4    4.2    3.8    4.0
4      Tiare Valdivia  12345678-5    5.0    5.5    5.2
5      Maikely Mejias  12345678-6    6.1    5.9    6.3
6      Emilia Fuentes  12345678-7    3.5    4.0    3.8
7     Vicente Araneda  12345678-8    5.8    6.0    5.5

In [26]:
# Información general del DataFrame: columnas, tipos de dato, cantidad de filas
notas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nombre  8 non-null      object
 1   rut     8 non-null      object
 2   nota1   8 non-null      float64
 3   nota2   8 non-null      float64
 4   nota3   8 non-null      float64
dtypes: float64(3), object(2)
memory usage: 452.0+ bytes

### Selección de filas y columnas

- `.loc[]` selecciona por **etiqueta** (nombre de columna, índice)
- `.iloc[]` selecciona por **posición** (como en una matriz)

In [27]:
# Una sola columna
print(notas["nombre"])

0           Anahis Friz
1       Vicente Araneda
2            Alonso Cea
3    Alenger Betancourt
4        Tiare Valdivia
5        Maikely Mejias
6        Emilia Fuentes
7       Vicente Araneda
Name: nombre, dtype: object

In [28]:
# Varias columnas
print(notas[["nombre", "nota1", "nota2"]])

               nombre  nota1  nota2
0         Anahis Friz    1.5    2.2
1     Vicente Araneda    3.9    4.1
2          Alonso Cea    6.8    6.5
3  Alenger Betancourt    4.2    3.8
4      Tiare Valdivia    5.0    5.5
5      Maikely Mejias    6.1    5.9
6      Emilia Fuentes    3.5    4.0
7     Vicente Araneda    5.8    6.0

In [29]:
# Por posición: primeras 3 filas, todas las columnas
print(notas.iloc[0:3, :])

            nombre         rut  nota1  nota2  nota3
0      Anahis Friz  12345678-1    1.5    2.2    4.8
1  Vicente Araneda  12345678-2    3.9    4.1    4.5
2       Alonso Cea  12345678-3    6.8    6.5    7.0

### Filtrado condicional

Esto es algo que con listas y bucles anidados sería mucho más largo de escribir.

In [30]:
# Estudiantes con nota1 menor a 4.0
reprobados_nota1 = notas[notas["nota1"] < 4.0]
print(reprobados_nota1)

            nombre         rut  nota1  nota2  nota3
0      Anahis Friz  12345678-1    1.5    2.2    4.8
1  Vicente Araneda  12345678-2    3.9    4.1    4.5
6   Emilia Fuentes  12345678-7    3.5    4.0    3.8

## Sistema de notas


**Tareas:**
1. Calcular el promedio de cada estudiante (columna nueva `promedio`)
2. Determinar si aprueba o no (nota mínima de aprobación: 4.0)
3. Ordenar el curso de mayor a menor promedio

In [33]:
# 1. Promedio por estudiante
notas["promedio"] = notas[["nota1", "nota2", "nota3"]].mean(axis=1).round(2)
notas

               nombre         rut  nota1  nota2  nota3  promedio
0         Anahis Friz  12345678-1    1.5    2.2    4.8      2.83
1     Vicente Araneda  12345678-2    3.9    4.1    4.5      4.17
2          Alonso Cea  12345678-3    6.8    6.5    7.0      6.77
3  Alenger Betancourt  12345678-4    4.2    3.8    4.0      4.00
4      Tiare Valdivia  12345678-5    5.0    5.5    5.2      5.23
5      Maikely Mejias  12345678-6    6.1    5.9    6.3      6.10
6      Emilia Fuentes  12345678-7    3.5    4.0    3.8      3.77
7     Vicente Araneda  12345678-8    5.8    6.0    5.5      5.77

In [34]:
# 2. Estado: Aprobado / Reprobado
notas["estado"] = notas["promedio"].apply(lambda p: "Aprobado" if p >= 4.0 else "Reprobado")
notas

               nombre         rut  nota1  nota2  nota3  promedio     estado
0         Anahis Friz  12345678-1    1.5    2.2    4.8      2.83  Reprobado
1     Vicente Araneda  12345678-2    3.9    4.1    4.5      4.17   Aprobado
2          Alonso Cea  12345678-3    6.8    6.5    7.0      6.77   Aprobado
3  Alenger Betancourt  12345678-4    4.2    3.8    4.0      4.00   Aprobado
4      Tiare Valdivia  12345678-5    5.0    5.5    5.2      5.23   Aprobado
5      Maikely Mejias  12345678-6    6.1    5.9    6.3      6.10   Aprobado
6      Emilia Fuentes  12345678-7    3.5    4.0    3.8      3.77  Reprobado
7     Vicente Araneda  12345678-8    5.8    6.0    5.5      5.77   Aprobado

In [37]:
# 3. Ordenar de mayor a menor promedio
ranking = notas.sort_values(by="promedio", ascending=False)
ranking[["nombre", "promedio", "estado"]]

               nombre  promedio     estado
2          Alonso Cea      6.77   Aprobado
5      Maikely Mejias      6.10   Aprobado
7     Vicente Araneda      5.77   Aprobado
4      Tiare Valdivia      5.23   Aprobado
1     Vicente Araneda      4.17   Aprobado
3  Alenger Betancourt      4.00   Aprobado
6      Emilia Fuentes      3.77  Reprobado
0         Anahis Friz      2.83  Reprobado

In [41]:
# ¿cuántos aprobaron y cuántos reprobaron?
print(notas["estado"].value_counts())

# Promedio general del curso
print(f"\nPromedio general del curso: {notas['promedio'].mean().round(2)}")

estado
Aprobado     6
Reprobado    2
Name: count, dtype: int64

Promedio general del curso: 4.83